### ISSUE TITLE
Newfoundland and Labrador's capital, St. John's, causes a syntax error

### ISSUE THREAD

**Issue by creidhne** [aggrolite/Geo-States#4]
The capital of Newfoundland and Labrador is St. John's. The apostrophe in the name causes a syntax error when looking for "NL" or "Newfoundland and Labrador". For example, `say $geo->find('NL')->text;` causes this syntax error:
```
Geo::States error: syntax error at (eval 2) line 3, near "'St. John's' };
sub text { 'Newfoundland and Labrador'"
  (Might be a runaway multi-line '' string starting on line 2)

```
The package is trying to evaluate this code:
```
package Geo::States::newfoundland::and::labrador;
sub text { 'NL' };
sub capital { 'St. John's' };
```
There is a similar problem for the District of Columbia, for example `say $geo->find('DC')->text;` causes:
```
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Geo/States.pm line 140.
District of Columbia
```

**Comment by aggrolite** [comment]
Thanks! 4a08c88c48c81c41d0c3eceaac40e196f485966d
